site_name: srepkg
site_url: https://duanegoodner.github.io/srepkg/
repo_url: https://github.com/duanegoodner/srepkg
repo_name: duanegoodner/srepkg
theme:
    name: material
markdown_extensions:
  - admonition
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Examples: examples.md
    - Comparing srepkg with pipx: compare_with_pipx.md

