name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade setuptools and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[test]

      - name: Ensure test directory has __init__.py
        run: |
          touch test/__init__.py

      - name: Clean previous coverage data
        run: |
          rm -rf .coverage coverage.xml .pytest_cache

      - name: Run tests with pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest --cov=srepkg --cov-report=xml --cov-branch -vv || (cat pytest.log && exit 1)

      - name: Upload coverage report  # ✅ Correct indentation
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: coverage.xml

      - name: Upload coverage to Codecov  # ✅ Correct indentation
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
